=== bnsubeva/XML/aphotecaryCatScheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="aphotecary">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="aphotecaryList" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="product" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Information">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="price" type="xs:integer" />
													<xs:element name="description" type="xs:string"/>
													<xs:element name="type" type="xs:string"/>
													<xs:element name="id" type="xs:integer"/>
													<xs:element name="typeId" type="xs:integer"/>
                                                    <xs:element name="composition" type="xs:string"/>
                                                    <xs:element name="instructions" type="xs:string"/>
													<xs:element name="comments" type="xs:string" minOccurs="0"/>
													<xs:element name="quantity" type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
				<xs:element name="typeList" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="typeInfo" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
										<xs:element name="typeName" type="xs:string"/>
                                        <xs:element name="type" maxOccurs="1">
                                             <xs:complexType>
												<xs:simpleContent>
												  <xs:extension base="xs:string">
													<xs:attribute type="xs:string" name="typeRef" />
													<xs:attribute type="xs:integer" name="typeIdRef" />
												  </xs:extension>
												</xs:simpleContent>
											 </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
	<xs:key name="typeKey">
            <xs:selector xpath="aphotecary/aphotecaryList/product/Information"/>
            <xs:field xpath="type"/>
            <xs:field xpath="typeId"/>
        </xs:key>
        <xs:keyref name="typeRef" refer="typeKey">
            <xs:selector xpath="aphotecary/typeList/typeInfo/type"/>
            <xs:field xpath="@typeRef"/>
            <xs:field xpath="@typeIdRef"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== bnsubeva/XML/aphotecaryCat.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="aphotecaryCatXslt.xsl"?>
<aphotecary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="aphotecaryCatScheme.xsd">
	<aphotecaryList>
		<product>
				<Information>
					 <name>WALMARK GINKOPRIM</name>
					 <price>23.84</price>
					 <description>GinkoPrim е уникална комбинация от Гинко билоба екстракт, диметиламиноетанол
                                (DMAE) и магнезий. Гинко билоба оказва благоприятен ефект върху кръвооросяването на мозъка
                                 и крайниците. По този начин подпомага паметта, концентрацията, намалява усещането за
                                 студени ръце и крака, поддържа зрението и слуха. DMAE е субстанция с естествен произход,
                                 която допринася за нормална умствена дейност. GinkoPrim съдържа и магнезий, който често е
                                 в недостатъчни количества в храната. Магнезият допринася за нормалното функциониране на
                                 нервната система и мускулите.
                     </description>
					 <type>Натурални добавки</type>
					 <id>1</id>
					 <typeId>10</typeId>
					 <composition>анти-слепващ агент: микрокристална целулоза, талк, магнезиев стеарат, магнезиев
                                 оксид, Гинко билоба екстракт, диметиламиноетанол битартарат, хидроксипропил целулоза,
                                 средноверижни триглицериди, стабилизатор: хидроксипропил метилцелулоза; оцветители:
                                 титаниев диоксид, рибофлавин, индиго кармин и брилянт синьо, шафранка концентрат.
					  </composition>
					 <instructions>1 таблетка дневно след хранене. С цел постигане на оптимален ефект
                                  препоръчваме GinkoPrim® да се приема в продължение на 2-3 месеца. Продуктът може да се
                                 приема и по-продължително време. Моля, консултирайте се с вашия лекуващ лекар. 
					 </instructions>
					 <comments>Да се съхранява на място, недостъпно за малки деца. Да се съхранява на сухо и
                               тъмно място при температура под 25 °C.
					 </comments>
					 <quantity>60</quantity>
				</Information>
		     </product>
			 
			 <product>
				<Information>
					 <name>LIERAC PREMIUM-противостареещи капсули</name>
					 <price>53.59</price>
					 <description> Lierac Premium Противостареещи капсули повишават дермалната и
                                  епидермалната регенерация. Серията Premium e 1-та пълна анти-ейдж програма, която
                                  отговаря на всички нужди на кожата и се грижи за нея както отвън, така и отвътре. Богати на
                                  скъпоценни масла, витамини и минерали, капсулите Premium помагат за ефективната защита
                                  на кожата от оксидативния стрес. Повишават дермалната и епидермалната регенерация като
                                  възстановяват тъканите чрез възпроизвеждане на действието на Foxo протеина.
								 </description>
					 <type>Натурални добавки</type>
					 <id>2</id>
					 <typeId>10</typeId>
					 <composition> Витамин Е, селен, арганово масло, масло от пореч, хиалуронова киселина, колаген.
                                  Капсула: желатин, вода и глицерин.
								  </composition>
					 <instructions> Приемайте 1 капсула дневно с достатъчно количество вода. Една опаковка
                                   съдържа 30 капсули и е достатъчна за едномесечен курс. Подходящи са за всички дами,
                                   независимо от възрастта, които желаят да забавят стареенето.
					 </instructions>
					 <comments> Съхранявайте на сухо и прохладно място при температура до 25 °C. Да не
                               се приема при свръхчувствителност към някоя от съставките. При бременност и кърмене се
                                консултирайте с лекар преди употреба.
					 </comments>
					 <quantity>30</quantity>
				</Information>
		     </product>
			 
			 <product>
				<Information>
					 <name>ABO PHARMA ABOGERIT</name>
					 <price>3.10</price>
					 <description> Витамин А допринася за поддържане на нормално зрение, кожа, нормално
                                  състояние на лигавиците, нормална функция на имунната система. Допринася за нормалното
                                  протичане на метаболизма на желязото и участва в процеса на специализация на клетките.
                                  Витамин Е допринася за защита на клетките от оксидативен стрес.
					 </description>
					 <type>Натурални добавки</type>
					 <id>3</id>
					 <typeId>10</typeId>
					 <composition>Витамин A /Ретинил палмитат/, Витамин Е /D-алфа токоферол/, Соево масло</composition>
					 <instructions> Възрастни и деца над 6 години да приемат по 1 капсула дневно. Капсулите
                                   се приемат без да се дъвчат с достатъчно течност, по време или след хранене.Този продукт
                                   не съдържа съставки от генно модифицирани организми (ГМО)! Да не се превишава
                                   препоръчителният дневен прием! Продуктът не е заместител на разнообразното хранене!
					 </instructions>
					 <comments>Да се съхранява на сухо и хладно място, недостъпно за деца!</comments>
					 <quantity>25</quantity>
				</Information>
		     </product>
			 
			 <product>
				<Information>
					 <name>PHYSIOMER-Ежедневен спрей за нос</name>
					 <price>10.98</price>
					 <description> При обилни секреции, дължащи се на настинка или други назални инфекции:
                                 Почиства, овлажнява и ефективно елиминира излишния секрет. Предотвратява УНГ усложнения
                                 (синузит, тонзилит). При ежедневна употреба: Елиминира прах, алергени, замърсители и патогени.
                                 Овлажнява назалната лигавица. Ефективно предпазва от настинка, грип и алергичен ринит.
                                 Използваният от PHYSIOMER иновативен производствен процес запазва съдържащите се
                                 минерали и микроелементи, както и ползите от тях в събираната край бреговете на Saint-Malo
                                 морска вода. На тях се дължи успокояващото и оздравително действие, с което продуктът
                                 превъзхожда обикновения физиологичен разтвор.
					 </description>
					 <type>Лекарства</type>
					 <id>4</id>
					 <typeId>20</typeId>
					 <composition>100% естествена, неразредена, изотонична, стерилна морска вода. Без консерванти.</composition>
					 <instructions> За хигиена и превенция: 1 до 2 пъти дневно; В случай на течащ и запушен
                                   нос: 4 до 6 пъти на ден. При възрастни и деца над 6 години - наклонете главата на една страна.
                                   Внимателно въведете накрайника в горната ноздра и направете едно впръскване. Оставете
                                   да подейства за няколко секунди. Повторете в другата ноздра. Издухайте носа. След всяко
                                   използване, измивайте накрайника с гореща вода и го подсушавайте.
                     </instructions>
					 <comments>Съхранявайте на място без достъп на деца.</comments>
					 <quantity>135</quantity>
				</Information>
		     </product>
			 
			 <product>
				<Information>
					 <name>PHYSIOMER-Бебе спрей за нос</name>
					 <price>10.98</price>
					 <description>   При ежедневно прилагане: Почиства, овлажнява и премахва излишните
									секрети; Премахва прах, замърсители, алергени, бактерии и вируси от ноздрите; С ефективно
									предпазващо действие срещу настинка и ринофарингит. При настинка или ринофарингит: Спомага
									за възстановяване на назалното дишане. Възпрепятства развитие на усложнения от бронхиолит и
									отит. Благодарение на Comfort Tip® и финото впръскване (без газово налягане), PHYSIOMER Baby
									е с по-меко действие и по-добре се понася от децата </description>
					 <type>Лекарства</type>
					 <id>5</id>
					 <typeId>20</typeId>
					 <composition>   стерилна, неразредена, изотонична, 100% естествена морска вода. Без консерванти.</composition>
					 <instructions>  Сложете бебето / новороденото да легне. Завъртете главата му на една страна,
									за да избегнете стичането на секрети надолу в гърлото. Внимателно въведете накрайника в
									горната ноздра и направете едно впръскване. Повторете в другата ноздра. Повдигнете бебето,
									за да изтекат секретите и избършете нослето. Измивайте накрайника с гореща вода след всяка
									употреба и го подсушавайте.
					 </instructions>
					 <comments> Използваният от PHYSIOMER иновативен производствен процес запазва
							съдържащите се минерали и микроелементи, както и ползите от тях в събираната край бреговете
							на Saint-Malo морска вода. На тях се дължи успокояващото и оздравително действие, с което
							продуктът превъзхожда обикновения физиологичен разтвор.
					 </comments>
					 <quantity>115</quantity>
				</Information>
		     </product>
			 
			 <product>
				<Information>
					 <name>ABO PHARMA LICHENSED-таблети за смучене за деца</name>
					 <price>5.72</price>
					 <description> Лихенсед Таблетки за деца е медицинско изделие, предназначено за облекчаване
								на възпалението на гърлото при болка, парене и чувствителност по време на преглъщане.
								Иновативната формула действа като бариера, създавайки защитен слой, който обхваща устната
								кухина, предпазвайки я от контакт с външни фактори с раздразнително действие. Подсилен с
								екстракт от Алое Вера, който спомага за поддържане на хидратацията на лигавицата. Лихенсед
								Таблетки за деца облекчава неприятните симптоми на възпаленото гърло.
					 </description>
					 <type>Лекарства</type>
					 <id>6</id>
					 <typeId>20</typeId>
